products/urls.py
from django.urls import path
from .views import ProductList , ProductDetail , BrandList , BrandDetail , CategoryList ,post_list

app_name = 'products'
urlpatterns = [
    path('test', post_list),
    path('', ProductList.as_view(), name='product_list'),
    path('<int:pk>', ProductDetail.as_view(), name='product_details'),
    path('brands/', BrandList.as_view(), name='brand_list'),
    path('brands/<int:pk>', BrandDetail.as_view(), name='brand_detail'),
    path('category/', CategoryList.as_view(), name='category_list'),


]

project/urls.py
from django.contrib import admin
from django.urls import path , include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('products/', include('products.urls',namespace='products')),
    path('summernote/', include('django_summernote.urls')),
    path('__debug__/', include('debug_toolbar.urls')),
]

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

accounts/models.py
from django.db import models

# Create your models here.

orders/models.py
from django.db import models

# Create your models here.

products/models.py
from django.db import models
from django.utils.translation import gettext as _
from django.utils import timezone
from django.contrib.auth.models import User
from taggit.managers import TaggableManager


# Create your models here.

PRODUCT_FLAC = (
    ('New' , 'New'),
    ('Feature' , 'Feature'),
    ('Sale' , 'Sale')
)

class Product(models.Model):
    name = models.CharField(_('Name'),max_length=100)
    sku = models.IntegerField(_('SKU'))
    subtitle = models.CharField(_('Subtitle'),max_length=300)
    desc = models.TextField(_('Description'),max_length=10000)
    flag = models.CharField(_('Flag'),max_length=10 , choices=PRODUCT_FLAC)
    price = models.FloatField(_('Price'))
    image = models.ImageField(upload_to='products')
    tags = TaggableManager()
    category = models.ForeignKey('Category' ,verbose_name=_('Category'), related_name='product_category',on_delete=models.SET_NULL , null=True,blank=True)
    brand = models.ForeignKey('Brand' , verbose_name=_('Brand') , related_name='product_brand',on_delete=models.SET_NULL , null=True,blank=True)
    video_url = models.URLField(null=True,blank=True)
    quantity = models.IntegerField(default=50)

    def __str__(self):
        return self.name


class ProductImages(models.Model):
    product = models.ForeignKey(Product,verbose_name=_('Product'),related_name='product_image',on_delete=models.CASCADE)
    image = models.ImageField(verbose_name=_('Image'),upload_to='productimages')

    def __str__(slef):
        return str(slef.product)

class Category(models.Model):
    name = models.CharField(_('Name'),max_length=100 )
    image = models.ImageField(_('Image'),upload_to='category')

    def __str__ (self):
        return self.name

class Brand(models.Model):
    name = models.CharField(_('Name'),max_length=100)
    image = models.ImageField(_('Image'),upload_to='brand')

    def __str__(slef):
        return slef.name

class ProductReview(models.Model):
    user = models.ForeignKey(User,related_name='user_review',on_delete=models.SET_NULL,null=True,blank=True)
    product = models.ForeignKey(Product, verbose_name=_('Product'), related_name='product_review',on_delete=models.SET_NULL , null=True,blank=True)
    rate = models.IntegerField(verbose_name=_('Rate'))
    review = models.CharField(verbose_name=_('Review'),max_length=300)
    create_at = models.DateTimeField(default=timezone.now)

    def __str__(slef):
        return str(slef.product)

settings/models.py
from django.db import models

# Create your models here.

class Company(models.Model):
    name = models.CharField(max_length=100)
    logo = models.ImageField(upload_to='company/')
    subtitle = models.CharField(max_length=500)
    fb_link = models.URLField(null=True , blank=True)
    tw_link = models.URLField(null=True , blank=True)
    ins_link = models.URLField(null=True , blank=True)
    address = models.TextField(max_length=200)
    phone_number = models.TextField(max_length=200)
    email = models.TextField(max_length=200)
    call_us = models.CharField(max_length=25)
    email_us = models.EmailField()

    def __str__(self):
        return self.name
    

accounts/views.py
from django.shortcuts import render

# Create your views here.

orders/views.py
from django.shortcuts import render

# Create your views here.

products/views.py
from django.shortcuts import render
from django.views.generic import ListView , DetailView
from .models import Product , ProductImages , Brand , Category
from django.db.models import Count , Q , F , Value # F لاستعمل العمود نستخدم  Q,لاستخدام الاستعلامات
from django.db.models.functions import Concat # لدمج عمودين مع بعض
# from django.db.models.aggregates import
# Create your views here.

def post_list(request):
    # price_lte=30 اصغر من او يساوي,price_lt=30 اصغرمن , price__gte=30 اكبر من او يساوي ,price__gt=30 اكبر من
    # objects = Product.objects.all()
    # objects = Product.objects.filter(price__range=(30,50))
    # objects = Product.objects.filter(price__range=(30,50))
    # objects = Product.objects.filter(category__id=10)
    # objects = Product.objects.filter(category__id__gt=10)
    # objects = Product.objects.filter(name__startswith='S')
    # objects = Product.objects.filter(name__endswith='e')
    # objects = Product.objects.filter(desc__isnull=True)
    # objects = Product.objects.filter(desc__isnull=True)
    # objects = Product.objects.filter(quantity__gt=10)

    # objects = Product.objects.filter(quantity__gt=10, price__gt=50)
    # # عند استخدام الكويري
    # objects = Product.objects.filter(
    #     Q(quantity__gt=10) & # | or & and ~ not equl
    #     ~Q(price__gt=50)
    # )

    # objects = Product.objects.filter(quantity=F('price')) # عند المقارنه بين عمودين
    # objects = Product.objects.filter(quantity=F('category__id'))
    # objects = Product.objects.order_by('name')
    # objects = Product.objects.order_by('-name')
    # objects = Product.objects.order_by('name','-price')
    # objects = Product.objects.filter(quantity=F('price')).order_by('-name')
    # لجلب عناصر محدده
    # objects = Product.objects.all().order_by('-name')[:10]
    # لجلب اول عنصر فقط first earliest end latest
    # objects = Product.objects.latest('name')
    # objects = Product.objects.all()[10:20]
    # data___Dectionary recovery
    # objects = Product.objects.values('id','name','category__name')
    # data___typle recovery
    # objects = Product.objects.values_list('id','name','category__name','brand')
    # objects = Product.objects.only('id','name')

    # objects = Product.objects.select_related('category').all() # one to one use select_related foreignkey
    # objects = Product.objects.prefetch_related('category').all() # many to many use prefetch_related

    # objects = Product.objects.annotate(is_new=Value(True)) # add new colum in model
    # objects = Product.objects.annotate(
    #     full_name = Concat('name',Value(' '),'flag')
    # ) # لدمج عمودين مع بعض

    # ----------    aggregates --------
    objects = Product.objects.annotate(is_new=Value(True))


    print(objects)


    return render(request, 'products/test_list.html',{'products':objects})


class ProductList(ListView):
    model = Product
    paginate_by = 100 #الصفحة المعروضة


class ProductDetail(DetailView):
    model = Product


    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        myproduct = self.get_object()
        context["images"] = ProductImages.objects.filter(product=myproduct)
        context['related'] = Product.objects.filter(category=myproduct.category)[:10]
        return context

class BrandList(ListView):
    model = Brand
    # paginate_by = 5
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['brands'] = Brand.objects.all().annotate(product_count=Count('product_brand'))
        return context



class BrandDetail(DetailView):
    model = Brand


    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        brand = self.get_object()
        context["brand_products"] = Product.objects.filter(brand=brand)
        return context


class CategoryList(ListView):
    model = Category
    # paginate_by = 3

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['category'] = Category.objects.all().annotate(product_count=Count('product_category'))
        return context

settings/views.py
from django.shortcuts import render

# Create your views here.

products/templates/products/brand_detail.html
{% extends 'base.html' %}
{% load static %}
{% block mystitac %}
    <link rel="stylesheet" href="{% static 'css/brand-single.css' %}">
{% endblock mystitac %}

{% block body %}

        <!--=====================================
                    BANNER PART START
        =======================================-->
        <section class="single-banner" style="background: url(images/single-banner.jpg) no-repeat center;">
            <div class="container">
                <h2>Brand Single</h2>
                <ol class="breadcrumb">
                    <li class="breadcrumb-item"><a href="index.html">Home</a></li>
                    <li class="breadcrumb-item"><a href="brand-list.html">brand-list</a></li>
                    <li class="breadcrumb-item active" aria-current="page">brand-single</li>
                </ol>
            </div>
        </section>
        <!--=====================================
                    BANNER PART END
        =======================================-->


        <!--=====================================
                  BRAND SINGLE PART START
        =======================================-->
        <div class="brand-single">
            <a href="#"><img src="{{brand.image.url}}" alt="brand"></a>
            <a href="#"><h3>{{brand}}</h3></a>
            <ul>
                <li class="fas fa-star active"></li>
                <li class="fas fa-star active"></li>
                <li class="fas fa-star active"></li>
                <li class="fas fa-star active"></li>
                <li class="fas fa-star"></li>
                <li class="total">(163 ratings)</li>
            </ul>
            <p>({{brand.product_count}} items)</p>
        </div>
        <!--=====================================
                  BRAND SINGLE PART END
        =======================================-->


        <!--=====================================
                    SHOP PART START
        =======================================-->
        <section class="inner-section shop-part">
            <div class="container">
                <div class="row">
                    <div class="col-lg-12">
                        <div class="top-filter">
                            <div class="filter-show">
                                <label class="filter-label">Show :</label>
                                <select class="form-select filter-select">
                                    <option value="1">12</option>
                                    <option value="2">24</option>
                                    <option value="3">36</option>
                                </select>
                            </div>
                            <div class="filter-short">
                                <label class="filter-label">Short by :</label>
                                <select class="form-select filter-select">
                                    <option selected>default</option>
                                    <option value="3">trending</option>
                                    <option value="1">featured</option>
                                    <option value="2">recommend</option>
                                </select>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="row row-cols-2 row-cols-md-3 row-cols-lg-3 row-cols-xl-5">
                    {% for product in brand_products %}
                        <div class="col">
                            <div class="product-card">
                                <div class="product-media">
                                    <div class="product-label">
                                        <label class="label-text new">{{product.flag}}</label>
                                    </div>
                                    <button class="product-wish wish">
                                        <i class="fas fa-heart"></i>
                                    </button>
                                    <a class="product-image" href="product-video.html">
                                        <img src="{{product.image.url}}" style="width: 100%;
                                        height: 15vw; background-position: center center !important;
                                        object-fit: cover;" alt="product">
                                    </a>
                                    <div class="product-widget">
                                        <a title="Product Compare" href="compare.html" class="fas fa-random"></a>
                                        <a title="Product Video" href="{{product.video_url}}" class="venobox fas fa-play" data-autoplay="true" data-vbtype="video"></a>
                                        <a title="Product View" href="#" class="fas fa-eye" data-bs-toggle="modal" data-bs-target="#product-view"></a>
                                    </div>
                                </div>
                                <div class="product-content">
                                    <div class="product-rating">
                                        <i class="active icofont-star"></i>
                                        <i class="active icofont-star"></i>
                                        <i class="active icofont-star"></i>
                                        <i class="active icofont-star"></i>
                                        <i class="icofont-star"></i>
                                        <a href="product-video.html">(3)</a>
                                    </div>
                                    <h6 class="product-name">
                                        <a href="{% url 'products:product_details' product.id %}">{{product}}</a>
                                    </h6>
                                    <h6 class="product-price">
                                        <del>$34</del>
                                        <span>${{product.price}}<small>/piece</small></span>
                                    </h6>
                                    <button class="product-add" title="Add to Cart">
                                        <i class="fas fa-shopping-basket"></i>
                                        <span>add</span>
                                    </button>
                                    <div class="product-action">
                                        <button class="action-minus" title="Quantity Minus"><i class="icofont-minus"></i></button>
                                        <input class="action-input" title="Quantity Number" type="text" name="quantity" value="1">
                                        <button class="action-plus" title="Quantity Plus"><i class="icofont-plus"></i></button>
                                    </div>
                                </div>
                            </div>
                        </div>
                    {% endfor %}
                </div>
                {% if is_paginated %}
                    <div class="row">
                        <div class="col-lg-12">
                            <div class="bottom-paginate">
                                <p class="page-info">Showing 12 of 60 Results</p>
                                <ul class="pagination">
                                    {% if page_obj.has_previous %}
                                        <li class="page-item">
                                            <a class="page-link" href="?page={{page_obj.previous_page_number}}">
                                                <i class="fas fa-long-arrow-alt-left"></i>
                                            </a>
                                        </li>
                                    {% else %}
                                        <li class="page-item disabled"><i class="fas fa-long-arrow-alt-left"></i></li>
                                    {% endif %}


                                    {% for i in paginator.page_range %}
                                        {% if page_obj.number == i %}
                                                <li class="page-item"><a class="page-link active" href="#">{{i}}</a></li>
                                        {% else %}
                                            <li class="page-item"><a class="page-link" href="?page={{i}}">{{i}}</a></li>
                                        {% endif %}

                                    {% endfor %}

                                    {% if page_obj.has_next %}
                                        <li class="page-item">
                                            <a class="page-link" href="?page={{page_obj.next_page_number}}">
                                                <i class="fas fa-long-arrow-alt-right"></i>
                                            </a>
                                        </li>
                                    {% else %}
                                        <li class="page-item disabled"></li>
                                    {% endif %}

                                </ul>
                            </div>
                        </div>
                    </div>
                {% endif %}
            </div>
        </section>
        <!--=====================================
                    SHOP PART END
        =======================================-->

{% endblock body %}

products/templates/products/brand_list.html
{% extends 'base.html' %}
{% load static %}

{% block mystitac %}
    <link rel="stylesheet" href="{% static 'css/brand-list.css' %}">
{% endblock mystitac %}

{% block body %}

        <!--=====================================
                    BANNER PART START
        =======================================-->
        <section class="inner-section single-banner" style="background: url(images/single-banner.jpg) no-repeat center;">
            <div class="container">
                <h2>brand list</h2>
                <ol class="breadcrumb">
                    <li class="breadcrumb-item"><a href="index.html">Home</a></li>
                    <li class="breadcrumb-item active" aria-current="page">brand-list</li>
                </ol>
            </div>
        </section>
        <!--=====================================
                    BANNER PART END
        =======================================-->


        <!--=====================================
                    BRAND LIST PART START
        =======================================-->
        <section class="inner-section">
            <div class="container">
                <div class="row">
                    <div class="col-lg-12">
                        <div class="top-filter">
                            <div class="filter-show">
                                <label class="filter-label">Show :</label>
                                <select class="form-select filter-select">
                                    <option value="1">12</option>
                                    <option value="2">24</option>
                                    <option value="3">36</option>
                                </select>
                            </div>
                            <div class="filter-short">
                                <label class="filter-label">Short by :</label>
                                <select class="form-select filter-select isotope-select">
                                    <option value="*">show all</option>
                                    <option value=".vegetables">vegetables</option>
                                    <option value=".fruits">fruits</option>
                                    <option value=".drinks">drinks</option>
                                    <option value=".fishes">fishes</option>
                                    <option value=".meats">meats</option>
                                </select>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="row row-cols-2 row-cols-md-3 row-cols-lg-4 row-cols-xl-5 isotope-items">
                    {% for brand in brands %}
                        <div class="col all vegetables">
                            <div class="brand-wrap">
                                <div class="brand-media">
                                    <img src="{{brand.image.url}}" alt="brand">
                                    <div class="brand-overlay">
                                        <a href="{% url 'products:brand_detail' brand.id %}"><i class="fas fa-link"></i></a>
                                    </div>
                                </div>
                                <div class="brand-meta">
                                    <h4>{{brand}}</h4>
                                    <p>({{brand.product_count}} items)</p>
                                </div>
                            </div>
                        </div>
                    {% endfor %}
                </div>
                {% if is_paginated %}
                <div class="row">
                    <div class="col-lg-12">
                        <div class="bottom-paginate">
                            <p class="page-info">Showing 12 of 60 Results</p>
                            <ul class="pagination">
                                {% if page_obj.has_previous %}
                                    <li class="page-item">
                                        <a class="page-link" href="?page={{page_obj.previous_page_number}}">
                                            <i class="fas fa-long-arrow-alt-left"></i>
                                        </a>
                                    </li>
                                {% else %}
                                    <li class="page-item disabled"><i class="fas fa-long-arrow-alt-left"></i></li>
                                {% endif %}


                                {% for i in paginator.page_range %}
                                    {% if page_obj.number == i %}
                                            <li class="page-item"><a class="page-link active" href="#">{{i}}</a></li>
                                    {% else %}
                                        <li class="page-item"><a class="page-link" href="?page={{i}}">{{i}}</a></li>
                                    {% endif %}

                                {% endfor %}

                                {% if page_obj.has_next %}
                                    <li class="page-item">
                                        <a class="page-link" href="?page={{page_obj.next_page_number}}">
                                            <i class="fas fa-long-arrow-alt-right"></i>
                                        </a>
                                    </li>
                                {% else %}
                                    <li class="page-item disabled"></li>
                                {% endif %}

                            </ul>
                        </div>
                    </div>
                </div>
                {% endif %}
            </div>
        </section>
        <!--=====================================
                    BRAND LIST PART END
        =======================================-->

{% endblock body %}

products/templates/products/category_list.html
{% extends 'base.html' %}
{% load static %}

{% block mystitac %}
    <link rel="stylesheet" href="{% static 'css/all-category.css' %}">
{% endblock mystitac %}

{% block body %}
        <!--=====================================
                    BANNER PART START
        =======================================-->
        <section class="inner-section single-banner" style="background: url(images/single-banner.jpg) no-repeat center;">
            <div class="container">
                <h2>all category</h2>
                <ol class="breadcrumb">
                    <li class="breadcrumb-item"><a href="index.html">Home</a></li>
                    <li class="breadcrumb-item active" aria-current="page">all-category</li>
                </ol>
            </div>
        </section>
        <!--=====================================
                    BANNER PART END
        =======================================-->


        <!--=====================================
                    CATEGORY PART START
        =======================================-->
        <section class="inner-section">
            <div class="container">
                <div class="row">
                    <div class="col-lg-12">
                        <div class="top-filter">
                            <div class="filter-show">
                                <label class="filter-label">Show :</label>
                                <select class="form-select filter-select">
                                    <option value="1">12</option>
                                    <option value="2">24</option>
                                    <option value="3">36</option>
                                </select>
                            </div>
                            <div class="filter-short">
                                <label class="filter-label">Short by :</label>
                                <select class="form-select filter-select">
                                    <option selected>default</option>
                                    <option value="3">trending</option>
                                    <option value="1">featured</option>
                                    <option value="2">recommend</option>
                                </select>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="row row-cols-2 row-cols-md-3 row-cols-lg-4 row-cols-xl-5 justify-content-center">
                    {% for cat in category %}
                        <div class="col">
                            <div class="category-wrap">
                                <div class="category-media">
                                    <img src="{{cat.image.url}} "style="width: 100%;
                                    height: 18vw;
                                    object-fit: cover;" alt="category">
                                    <div class="category-overlay">
                                        <a href="shop-3column.html"><i class="fas fa-link"></i></a>
                                    </div>
                                </div>
                                <div class="category-meta">
                                    <h4>{{cat}}</h4>
                                    <p>({{cat.product_count}} items)</p>
                                </div>
                            </div>
                        </div>
                    {% endfor %}
                </div>
                {% if is_paginated %}
                    <div class="row">
                        <div class="col-lg-12">
                            <div class="bottom-paginate">
                                <p class="page-info">Showing 12 of 60 Results</p>
                                <ul class="pagination">
                                    {% if page_obj.has_previous %}
                                        <li class="page-item">
                                            <a class="page-link" href="?page={{page_obj.previous_page_number}}">
                                                <i class="fas fa-long-arrow-alt-left"></i>
                                            </a>
                                        </li>
                                    {% else %}
                                        <li class="page-item disabled"><i class="fas fa-long-arrow-alt-left"></i></li>
                                    {% endif %}


                                    {% for i in paginator.page_range %}
                                        {% if page_obj.number == i %}
                                                <li class="page-item"><a class="page-link active" href="#">{{i}}</a></li>
                                        {% else %}
                                            <li class="page-item"><a class="page-link" href="?page={{i}}">{{i}}</a></li>
                                        {% endif %}

                                    {% endfor %}

                                    {% if page_obj.has_next %}
                                        <li class="page-item">
                                            <a class="page-link" href="?page={{page_obj.next_page_number}}">
                                                <i class="fas fa-long-arrow-alt-right"></i>
                                            </a>
                                        </li>
                                    {% else %}
                                        <li class="page-item disabled"></li>
                                    {% endif %}

                                </ul>
                            </div>
                        </div>
                    </div>
                {% endif %}
            </div>
        </section>
        <!--=====================================
                    CATEGORY PART END
        =======================================-->

{% endblock body%}

products/templates/products/test_list.html
<!DOCTYPE html>
<html lang="en">
<head>
        <meta charset="UTF-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <title>test_list</title>
</head>
<body>
        <ul>
                {% for product in products %}
                        <li>{{product}}-{{product.price}}</li>
                {% endfor %}
        </ul>
</body>
</html>